services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - /src
      - /node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis-docker
      - REDIS_PORT=6379
    depends_on:
      - redis-docker
  redis-docker:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - redisData:/data

volumes:
  redisData: