version: '3'

services:
  web:
    image: "ubuntu"
    build: .
    command: tail -f /dev/null
    ports:
      - "8000:5000"
    volumes:
      - ./web_src:/tmp/src
        
    environment:
      - NODE_ENV=development
    depends_on:
      - redis  # Ensure Redis service starts before web

  redis:
    image: "redis:alpine"  # Use Redis Alpine for a lightweight image
    ports:
      - "6379:6379"  # Redis default port
    volumes:
      - ./redis_config:/tmp/redis_config

