version: '3'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    develop:
      - action: sync
        path: .
        target: .
        
    environment:
      - NODE_ENV=development
    depends_on:
      - redis  # Ensure Redis service starts before web

  redis:
    image: "redis:alpine"  # Use Redis Alpine for a lightweight image
    ports:
      - "6379:6379"  # Redis default port

