version: '3'
services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/src
      - /node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  redis:
    image: "redis:latest"
    ports:
      - "3030:3030"
